<!-- CSS Pseudo-classes https<item>//developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes -->

<item>active</item>
<item>any</item>
<item>checked</item>
<item>default</item>
<item>dir</item>
<item>disabled</item>
<item>empty</item>
<item>enabled</item>
<item>first</item>
<item>first-child</item>
<item>first-of-type</item>
<item>fullscreen</item>
<item>focus</item>
<item>hover</item>
<item>indeterminate</item>
<item>in-range</item>
<item>invalid</item>
<item>lang</item>
<item>last-child</item>
<item>last-of-type</item>
<item>left</item>
<item>link</item>
<item>not</item>
<item>nth-child</item>
<item>nth-last-child</item>
<item>nth-last-of-type</item>
<item>nth-of-type</item>
<item>only-child</item>
<item>only-of-type</item>
<item>optional</item>
<item>out-of-range</item>
<item>read-only</item>
<item>read-write</item>
<item>required</item>
<item>right</item>
<item>root</item>
<item>scope</item>
<item>target</item>
<item>valid</item>
<item>visited</item>
