<!-- https://www.w3.org/Style/CSS/all-properties -->
<item> azimuth </item>
<item> align-content </item>
<item> align-items </item>
<item> align-self </item>
<item> alignment-baseline </item>
<item> all </item>
<item> animation-name </item>
<item> animation-duration </item>
<item> animation-iteration-count </item>
<item> animation-direction </item>
<item> animation-delay </item>
<item> animation-play-state </item>
<item> animation-fill-mode </item>
<item> animation-timing-function </item>
<item> backface-visibility </item>
<item> background </item>
<item> background-attachment </item>
<item> background-blend-mode </item>
<item> background-break </item>
<item> background-clip </item>
<item> background-color </item>
<item> background-image </item>
<item> background-origin </item>
<item> background-position </item>
<item> background-repeat </item>
<item> background-size </item>
<item> baseline-shift </item>
<item> bookmark-label </item>
<item> bookmark-level </item>
<item> bookmark-level </item>
<item> border </item>
<item> border-bottom </item>
<item> border-bottom-color </item>
<item> border-bottom-image </item>
<item> border-bottom-style </item>
<item> border-bottom-width </item>
<item> border-bottom-left-image </item>
<item> border-bottom-left-radius </item>
<item> border-bottom-right-image </item>
<item> border-bottom-right-radius </item>
<item> border-boundary </item>
<item> border-collapse </item>
<item> border-color </item>
<item> border-corner-image </item>
<item> border-image </item>
<item> border-image-outset </item>
<item> border-image-repeat </item>
<item> border-image-slice </item>
<item> border-image-source </item>
<item> border-image-width </item>
<item> border-left </item>
<item> border-left-color </item>
<item> border-left-image </item>
<item> border-left-style </item>
<item> border-left-width </item>
<item> border-radius </item>
<item> border-right </item>
<item> border-right-color </item>
<item> border-right-image </item>
<item> border-right-style </item>
<item> border-right-width </item>
<item> border-spacing </item>
<item> border-style </item>
<item> border-top </item>
<item> border-top-color </item>
<item> border-top-image </item>
<item> border-top-style </item>
<item> border-top-width </item>
<item> border-top-left-image </item>
<item> border-top-left-radius </item>
<item> border-top-right-image </item>
<item> border-top-right-radius </item>
<item> border-width </item>
<item> bottom </item>
<item> box-align </item>
<item> box-decoration-break </item>
<item> box-direction </item>
<item> box-flex </item>
<item> box-shadow </item>
<item> box-sizing </item>
<item> box-snap </item>
<item> box-suppress </item>
<item> break-after </item>
<item> break-before </item>
<item> break-inside </item>
<item> caret-color </item>
<item> caption-side </item>
<item> chains </item>
<item> clear </item>
<item> clip </item>
<item> clip-path </item>
<item> clip-rule </item>
<item> color </item>
<item> color-interpolation-filters </item>
<item> column-count </item>
<item> column-fill </item>
<item> column-gap </item>
<item> column-rule </item>
<item> column-rule-color </item>
<item> column-rule-style </item>
<item> column-rule-width </item>
<item> column-span </item>
<item> column-width </item>
<item> columns </item>
<item> content </item>
<item> counter-increment </item>
<item> counter-reset </item>
<item> counter-set </item>
<item> cue </item>
<item> cue-after </item>
<item> cue-before </item>
<item> cursor </item>
<item> direction </item>
<item> display </item>
<item> dominant-baseline </item>
<item> elevation </item>
<item> empty-cells </item>
<item> filter </item>
<item> flex </item>
<item> flex-basis </item>
<item> flex-direction </item>
<item> flex-flow </item>
<item> flex-grow </item>
<item> flex-shrink </item>
<item> flex-wrap </item>
<item> float </item>
<item> flood-color </item>
<item> flood-opacity </item>
<item> flow </item>
<item> flow-from </item>
<item> flow-into </item>
<item> font </item>
<item> font-family </item>
<item> font-size </item>
<item> font-size-adjust </item>
<item> font-stretch </item>
<item> font-style </item>
<item> font-variant </item>
<item> font-weight </item>
<item> font-feature-settings </item>
<item> font-kerning </item>
<item> font-language-override </item>
<item> font-synthesis </item>
<item> font-variant-alternates </item>
<item> font-variant-caps </item>
<item> font-variant-east-asian </item>
<item> font-variant-ligatures </item>
<item> font-variant-numeric </item>
<item> font-variant-position </item>
<item> footnote-display </item>
<item> footnote-policy </item>
<item> glyph-orientation-vertical </item>
<item> grid </item>
<item> grid-area </item>
<item> grid-auto-columns </item>
<item> grid-auto-flow </item>
<item> grid-auto-rows </item>
<item> grid-column </item>
<item> grid-column-end </item>
<item> grid-column-gap </item>
<item> grid-column-start </item>
<item> grid-gap </item>
<item> grid-row </item>
<item> grid-row-end </item>
<item> grid-row-gap </item>
<item> grid-row-start </item>
<item> grid-template </item>
<item> grid-template-areas </item>
<item> grid-template-columns </item>
<item> grid-template-rows </item>
<item> hanging-punctuation </item>
<item> height </item>
<item> hyphens </item>
<item> image-orientation </item>
<item> image-rendering </item>
<item> image-resolution </item>
<item> initial-letter </item>
<item> initial-letter-align </item>
<item> initial-letter-wrap </item>
<item> isolation </item>
<item> justify-content </item>
<item> justify-items </item>
<item> justify-self </item>
<item> left </item>
<item> letter-spacing </item>
<item> lighting-color </item>
<item> linear-gradient </item>
<item> line-grid </item>
<item> line-height </item>
<item> line-snap </item>
<item> list-style </item>
<item> list-style-image </item>
<item> list-style-keyword </item>
<item> list-style-position </item>
<item> list-style-type  </item>
<item> margin </item>
<item> margin-bottom </item>
<item> margin-left </item>
<item> margin-right </item>
<item> margin-top </item>
<item> marker-offset </item>
<item> marker-side </item>
<item> marquee-direction </item>
<item> marquee-loop </item>
<item> marquee-speed </item>
<item> marquee-style </item>
<item> mask </item>
<item> mask-border </item>
<item> mask-border-mode </item>
<item> mask-border-outset </item>
<item> mask-border-repeat </item>
<item> mask-border-slice </item>
<item> mask-border-source </item>
<item> mask-border-width </item>
<item> mask-clip </item>
<item> mask-composite </item>
<item> mask-image </item>
<item> mask-mode </item>
<item> mask-origin </item>
<item> mask-position </item>
<item> mask-repeat </item>
<item> mask-size </item>
<item> mask-type </item>
<item> max-height </item>
<item> max-lines </item>
<item> max-width </item>
<item> min-height </item>
<item> min-width </item>
<item> mix-blend-mode </item>
<item> nav-down </item>
<item> nav-left </item>
<item> nav-right </item>
<item> nav-up </item>
<item> object-fit </item>
<item> object-position </item>
<item> offset-after </item>
<item> offset-before </item>
<item> offset-end </item>
<item> offset-start </item>
<item> opacity </item>
<item> order </item>
<item> orphans </item>
<item> outline </item>
<item> outline-color </item>
<item> outline-offset </item>
<item> outline-style </item>
<item> outline-width </item>
<item> overflow </item>
<item> overflow-style </item>
<item> overflow-wrap </item>
<item> overflow-x </item>
<item> overflow-y </item>
<item> padding </item>
<item> padding-bottom </item>
<item> padding-left </item>
<item> padding-right </item>
<item> padding-top </item>
<item> page </item>
<item> page-break-after </item>
<item> page-break-before </item>
<item> page-break-inside </item>
<item> pause </item>
<item> pause-after </item>
<item> pause-before </item>
<item> perspective </item>
<item> perspective-origin </item>
<item> pitch </item>
<item> pitch-range </item>
<item> play-during </item>
<item> pointer-events </item>
<item> polar-anchor </item>
<item> polar-angle </item>
<item> polar-distance </item>
<item> polar-origin </item>
<item> position </item>
<item> presentation-level </item>
<item> quotes </item>
<item> resize </item>
<item> rest </item>
<item> rest-after </item>
<item> rest-before </item>
<item> richness </item>
<item> right </item>
<item> rotation </item>
<item> rotation-point </item>
<item> ruby-align </item>
<item> ruby-merge </item>
<item> ruby-position </item>
<item> running </item>
<item> scroll-behavior </item>
<item> scroll-snap-align </item>
<item> scroll-snap-margin </item>
<item> scroll-snap-margin-block </item>
<item> scroll-snap-margin-block-end </item>
<item> scroll-snap-margin-block-start </item>
<item> scroll-snap-margin-bottom </item>
<item> scroll-snap-margin-inline </item>
<item> scroll-snap-margin-inline-end </item>
<item> scroll-snap-margin-inline-start </item>
<item> scroll-snap-margin-left </item>
<item> scroll-snap-margin-right </item>
<item> scroll-snap-margin-top </item>
<item> scroll-snap-padding </item>
<item> scroll-snap-padding-block </item>
<item> scroll-snap-padding-block-end </item>
<item> scroll-snap-padding-block-start </item>
<item> scroll-snap-padding-bottom </item>
<item> scroll-snap-padding-inline </item>
<item> scroll-snap-padding-inline-end </item>
<item> scroll-snap-padding-inline-start </item>
<item> scroll-snap-padding-left </item>
<item> scroll-snap-padding-right </item>
<item> scroll-snap-padding-top </item>
<item> scroll-snap-stop </item>
<item> scroll-snap-type </item>
<item> shape-image-threshold </item>
<item> shape-inside </item>
<item> shape-margin </item>
<item> shape-outside </item>
<item> size </item>
<item> speak </item>
<item> speak-as </item>
<item> speak-header </item>
<item> speak-numeral </item>
<item> speak-punctuation </item>
<item> speech-rate </item>
<item> stress </item>
<item> string-set </item>
<item> tab-size </item>
<item> table-layout </item>
<item> text-align </item>
<item> text-align-last </item>
<item> text-combine-upright </item>
<item> text-decoration </item>
<item> text-decoration-color </item>
<item> text-decoration-line </item>
<item> text-decoration-skip </item>
<item> text-decoration-style </item>
<item> text-emphasis </item>
<item> text-emphasis-color </item>
<item> text-emphasis-position </item>
<item> text-emphasis-style </item>
<item> text-indent </item>
<item> text-justify </item>
<item> text-orientation </item>
<item> text-overflow </item>
<item> text-shadow </item>
<item> text-transform </item>
<item> text-underline-position </item>
<item> text-wrap </item>
<item> top </item>
<item> transform </item>
<item> transform-origin </item>
<item> transform-style </item>
<item> transition </item>
<item> transition-delay </item>
<item> transition-property </item>
<item> transition-duration </item>
<item> transition-timing-function </item>
<item> unicode-bidi </item>
<item> vertical-align </item>
<item> visibility </item>
<item> voice-balance </item>
<item> voice-duration </item>
<item> voice-family </item>
<item> voice-pitch </item>
<item> voice-range </item>
<item> voice-rate </item>
<item> voice-stress </item>
<item> voice-volume </item>
<item> volume </item>
<item> white-space </item>
<item> widows </item>
<item> width </item>
<item> will-change </item>
<item> word-break </item>
<item> word-spacing </item>
<item> word-wrap </item>
<item> wrap-flow </item>
<item> wrap-through </item>
<item> writing-mode </item>
<item> z-index </item>

<!-- @font-face https://drafts.csswg.org/css-fonts/#at-font-face-rule -->
<item> font-family </item>
<item> src </item>
<item> font-size </item>
<item> font-stretch </item>
<item> font-style </item>
<item> font-variant-ligatures </item>
<item> font-variant-position </item>
<item> font-variant-caps </item>
<item> font-variant-numeric </item>
<item> font-variant-alternates </item>
<item> font-weight </item>
<item> font-kerning </item>
<item> unicode-range </item>
